export const customData  = [
    {

        product_without_cp:[
            {
                SKU:"123",
                itemNo:"product_1",
                qty_Sold:"1",
                
                selling_price:"2",
                markup:"2",
                saleAmount:"3",
                profit:"2"
            },
            {
                SKU:"321",
                itemNo:"product_2",
                qty_Sold:"2",
               
                selling_price:"3",
                markup:"2",
                saleAmount:"4",
                profit:"3"
            }
        ],

        TotalMarkup:"no data",
        TotalAvgMarkup:"no data",
        TotalSales:"no data",
        TotalProfit:"no data",
        TotalQtySold:"no data",

        below_20_percentage:[
            {
                SKU:"123",
                itemNo:"product_1",
                qty_Sold:"1",
                cost_price:"1",
                selling_price:"2",
                markup:"2",
                saleAmount:"3",
                profit:"2"
            },
            {
                SKU:"321",
                itemNo:"product_2",
                qty_Sold:"2",
                cost_price:"2",
                selling_price:"3",
                markup:"2",
                saleAmount:"4",
                profit:"3"
            }
        ],
        _20_to_30_percentage:[
            {
                SKU:"123",
                itemNo:"product_1",
                qty_Sold:"1",
                cost_price:"1",
                selling_price:"2",
                markup:"2",
                saleAmount:"3",
                profit:"2"
            },
            {
                SKU:"321",
                itemNo:"product_2",
                qty_Sold:"2",
                cost_price:"2",
                selling_price:"3",
                markup:"2",
                saleAmount:"4",
                profit:"3"
            }
        ],
        _30_to_40_percentage:[
            {
                SKU:"123",
                itemNo:"product_1",
                qty_Sold:"1",
                cost_price:"1",
                selling_price:"2",
                markup:"2",
                saleAmount:"3",
                profit:"2"
            },
            {
                SKU:"321",
                itemNo:"product_2",
                qty_Sold:"2",
                cost_price:"2",
                selling_price:"3",
                markup:"2",
                saleAmount:"4",
                profit:"3"
            }
        ],
        _40_to_50_percentage:[
            {
                SKU:"123",
                itemNo:"product_1",
                qty_Sold:"1",
                cost_price:"1",
                selling_price:"2",
                markup:"2",
                saleAmount:"3",
                profit:"2"
            },
            {
                SKU:"321",
                itemNo:"product_2",
                qty_Sold:"2",
                cost_price:"2",
                selling_price:"3",
                markup:"2",
                saleAmount:"4",
                profit:"3"
            }
        ],
        above_50_percentage:[
            {
                SKU:"123",
                itemNo:"product_1",
                qty_Sold:"1",
                cost_price:"1",
                selling_price:"2",
                markup:"2",
                saleAmount:"3",
                profit:"2"
            },
            {
                SKU:"321",
                itemNo:"product_2",
                qty_Sold:"2",
                cost_price:"2",
                selling_price:"3",
                markup:"2",
                saleAmount:"4",
                profit:"3"
            }
        ],
        sales_Acc_Department:[
            {
                department_1:[
                    {
                        SKU:"123",
                        itemNo:"product_1",
                        qty_Sold:"1",
                        cost_price:"1",
                        selling_price:"2",
                        markup:"2",
                        saleAmount:"3",
                        profit:"2"
                    },
                    {
                        SKU:"321",
                        itemNo:"product_2",
                        qty_Sold:"2",
                        cost_price:"2",
                        selling_price:"3",
                        markup:"2",
                        saleAmount:"4",
                        profit:"3"
                    } 
                ],
                department_2:[
                    {
                        SKU:"123",
                        itemNo:"product_1",
                        qty_Sold:"1",
                        cost_price:"1",
                        selling_price:"2",
                        markup:"2",
                        saleAmount:"3",
                        profit:"2"
                    },
                    {
                        SKU:"321",
                        itemNo:"product_2",
                        qty_Sold:"2",
                        cost_price:"2",
                        selling_price:"3",
                        markup:"2",
                        saleAmount:"4",
                        profit:"3"
                    } 
                ],
            }
        ],
    }
]